config/routes.rb
Proedm::Application.routes.draw do

  get "confirmation/confirmation"

  resources :folders

  resources :categories

  resources :pushes do
    get :export, :on => :member
    match :start, :on => :member
    match :show_data, :on => :member
  end

  resources :designs do
    get :preview, :on => :member
    get :save, :on => :member
  end
  resources :address_books do
    get :export, :on => :member
    match :import, :on => :member
    get :show_data, :on => :member
  end

  resources :user do
    get :show_current, :on => :collection
    get :edit_password,:on => :collection

  end
  resources :collect do
    get :show_current, :on => :collection
    get :edit_password,:on => :collection

  end

  resources :contacts

  resources :events do
    match 'postback',:on => :collection
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "admin/index"

  devise_for :users, :controllers => {:sessions => "sessions"}

  get "home/index"

  match "confirmation/confirmation", :as => "confirmation"
  match "confirmation/back", :as => "back"

  root :to => "pushes#index"

end

app/models/design.rb
# -*- encoding : utf-8 -*-
class Design < ActiveRecord::Base
  acts_as_audited
  include UserResource
  validates_presence_of :name
end

app/controllers/designs_controller.rb
# -*- encoding : utf-8 -*-
class DesignsController < InheritedResources::Base
  skip_before_filter :authenticate_user!, :only => :preview
  load_and_authorize_resource :except=>:preview
  def index
    @designs = Design.with_user
  end

  def save
    @design = Design.find(params[:id])
    authorize! :read, @design

    if current_user.can_view(@design)
      #headers['Content-Type'] = "application/octet-stream" # I've also seen this for CSV files: 'text/csv; charset=iso-8859-1; header=present'
      #headers['Content-Disposition'] = "attachment; filename=\"#{@design.name}.html\""
      #send_data @design.html
      send_data @design.html, :type => "application/octet-stream",:filename => "#{@design.name}.html"
    else
      redirect_to designs_path, :notice=> "You don't have permissions for saving this design"
      #flash[:notice] = "You don't have permissions for previewing this design"
      #index
      #render :index
    end
  end

  def preview
    @design = Design.find(params[:id])
    #authorize! :read, @design, everyone can read
    #if current_user && current_user.can_view(@design)
      render :text => @design.html.html_safe
    #else
    #  redirect_to designs_path, :notice=> "You don't have permissions for previewing this design"
      #flash[:notice] = "You don't have permissions for previewing this design"
      #index
      #render :index
    #end
  end

  def update
    super
  end
end

app/helpers/designs_helper.rb
# -*- encoding : utf-8 -*-
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "New Design Name" %><br />
    <%= f.text_field :name %>
  </div>
    <br /><hr />
  <div class="field">
    <%= f.label :html, "Paste HTML Code" %><br />
    <%= f.kindeditor :html %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<div class="span-3">
  <div class="button">
    <%= link_to "Add Design", new_design_path(:type=>"new") %>
  </div>
</div>

<hr class="space"/>
<h2 style="color:#999">Design List</h2>
<hr/>
<div class="span-24">
  <p>Below is a summary of the design documents that are currently in your account. To view or modify an existing design
    document, just click the name. To add a new design, simply click “Add New Design”.</p>
</div>
<hr/>
<div id="container">
  <div id="demo">
    <table cellpadding="0" cellspacing="0" border="0" class="display" id="datagrid">
      <thead>
      <tr>
        <th>Design Title</th>
        <th>Design Created</th>
        <th>Design Modified</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @designs.each do |design| %>
          <tr class="gradeA">
            <td><%= link_to design.name, design %></td>
            <td><%= design.created_at %></td>
            <td><%= design.updated_at %></td>
            <td class="center">
              <%= link_to "Save", save_design_path(design) %>
              &nbsp;&nbsp;|&nbsp;&nbsp;
              <%= link_to "Preview", preview_design_path(design) %>
              &nbsp;&nbsp;|&nbsp;&nbsp;
              <%= link_to 'Edit', edit_design_path(design) %>
              &nbsp;&nbsp;|&nbsp;&nbsp;
              <%= link_to 'Delete', design, :confirm => 'Are you sure?', :method => :delete %>

            </td>
          </tr>
      <% end %>

      </tbody>
      <tfoot>
      <tr>
        <th>Design Title</th>
        <th>Design Created</th>
        <th>Design Modified</th>
        <th>Action</th>
      </tr>
      </tfoot>
    </table>
  </div>
  <div class="spacer"></div>
</div>

app/views/designs/new.html.erb
<div class="span-12">
  <fieldset>
    <legend><h4>Create Design</h4></legend>

    <%= render 'form' %>

  </fieldset>
</div>

<div class="span-12 last">
        <fieldset>
          <legend><h4>Note</h4></legend>
          <ul id="content-designF">
          <p><%= link_to image_tag("help/edm.png", :class=>"edm"), root_url %></p>
        </fieldset>
 	</div>

app/views/designs/show.html.erb
<br/><br/>
<div class="span-24">
  <form id="dummy" action="" method="post">
    <h3><%= @design.name %></h3>
    <fieldset>
      <div class="span-24">
        <h6>Copy URL</h6>
        <abbr style="color:#666"><%=Rails.configuration.action_mailer.default_url_options[:host]%><%= url_for  @design %></abbr>
      </div>
      <hr class="space">
      <hr/>
      <iframe src="<%=url_for preview_design_path(@design) %>" width=1000 height=1200 ></iframe>

      <hr class="space">
      <hr/>

      <script type="text/javascript">
          function goto() {
              location.href = "/designs";
          }
      </script>


      <input type="button" value="Back" onclick="goto();"/>
    </fieldset>
  </form>
</div>