config/routes.rb
Proedm::Application.routes.draw do

  get "confirmation/confirmation"

  resources :folders

  resources :categories

  resources :pushes do
    get :export, :on => :member
    match :start, :on => :member
    match :show_data, :on => :member
  end

  resources :designs do
    get :preview, :on => :member
    get :save, :on => :member
  end
  resources :address_books do
    get :export, :on => :member
    match :import, :on => :member
    get :show_data, :on => :member
  end

  resources :user do
    get :show_current, :on => :collection
    get :edit_password,:on => :collection

  end
  resources :collect do
    get :show_current, :on => :collection
    get :edit_password,:on => :collection

  end

  resources :contacts

  resources :events do
    match 'postback',:on => :collection
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "admin/index"

  devise_for :users, :controllers => {:sessions => "sessions"}

  get "home/index"

  match "confirmation/confirmation", :as => "confirmation"
  match "confirmation/back", :as => "back"

  root :to => "pushes#index"

end

app/models/folder.rb
# -*- encoding : utf-8 -*-
class Folder < ActiveRecord::Base
  acts_as_audited
end

app/controllers/folders_controller.rb
# -*- encoding : utf-8 -*-
class FoldersController < InheritedResources::Base
  before_filter :authenticate_admin_user
end

app/helpers/folders_helper.rb
# -*- encoding : utf-8 -*-
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :html %><br />
    <%= f.text_area :html %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<h1>Listing folders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Html</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @folders.each do |folder| %>
  <tr>
    <td><%= folder.name %></td>
    <td><%= folder.html %></td>
    <td><%= link_to 'Show', folder %></td>
    <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
    <td><%= link_to 'Destroy', folder, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @folder.name %>
</p>

<p>
  <b>Html:</b>
  <%= @folder.html %>
</p>


<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>