config/routes.rb
Proedm::Application.routes.draw do

  get "confirmation/confirmation"

  resources :folders

  resources :categories

  resources :pushes do
    get :export, :on => :member
    match :start, :on => :member
    match :show_data, :on => :member
  end

  resources :designs do
    get :preview, :on => :member
    get :save, :on => :member
  end
  resources :address_books do
    get :export, :on => :member
    match :import, :on => :member
    get :show_data, :on => :member
  end

  resources :user do
    get :show_current, :on => :collection
    get :edit_password,:on => :collection

  end
  resources :collect do
    get :show_current, :on => :collection
    get :edit_password,:on => :collection

  end

  resources :contacts

  resources :events do
    match 'postback',:on => :collection
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "admin/index"

  devise_for :users, :controllers => {:sessions => "sessions"}

  get "home/index"

  match "confirmation/confirmation", :as => "confirmation"
  match "confirmation/back", :as => "back"

  root :to => "pushes#index"

end

app/models/address_book.rb
# -*- encoding : utf-8 -*-
class AddressBook < ActiveRecord::Base
  acts_as_audited
  scope :active, where(:step=>nil)
  include UserResource

  has_many :contacts,:dependent => :destroy


  attr_accessor :disable_validation

  validates_presence_of :name, :if => lambda { |o| o.step == "name" && !disable_validation }

  mount_uploader :import_file, ImporterUploader

  def steps

     ["name", "agree_provision"]
  end

  def next_step
    self.step = steps[steps.index(self.step)+1]
  end

  def previous_step
    self.step = steps[steps.index(self.step)-1]
  end


end

app/controllers/address_books_controller.rb
# -*- encoding : utf-8 -*-
require 'csv'
require 'csv_importer'
class AddressBooksController < InheritedResources::Base
  load_and_authorize_resource :except => [:export, :import, :show_data]

  def index
    @address_books = AddressBook.with_user.active

  end

  def new
    @address_book = current_address_book
    if @address_book && params[:type] == "new"
      @address_book.destroy
      @address_book = nil
    end
    @address_book ||= AddressBook.new
    @address_book.instance_variable_set("@new_record", true)
  end


  def create


    @address_book = current_address_book
    @address_book ||= AddressBook.new
    if params[:address_book] && params[:address_book][:name].present?
      @address_book.name = params[:address_book][:name]
    end
    @address_book.update_attributes(params[:address_book])


    if @address_book.save
      @address_book.next_step
      @address_book.disable_validation = true
      @address_book.save!

      if @address_book.step.nil? #last_step
        redirect_to import_address_book_path(@address_book)
        return
      end
    end


    @address_book.instance_variable_set("@new_record", true)
    render "new"


  end

  def export
    @address_book = AddressBook.find(params[:id])
    authorize! :read, @address_book

    csv_string = CSV.generate do |csv|
      csv << ["email", "firstname", "lastname", "name"]
      @address_book.contacts.each do |contact|
        csv << [contact.email, contact.firstname, contact.lastname, contact.name]
      end
      # ...
    end

    send_data csv_string, :type => "text/csv", :filename => "#{@address_book.name}.csv", :disposition => "inline"

  end

  def import

   require 'address_book'
   require 'contact'


    @address_book = AddressBook.find(params[:id])

   #Excon.ssl_verify_peer = false
    @contacts_value = "=\n"
    if request.get?
       @uploader = @address_book.import_file
       @uploader.success_action_redirect = url_for(:controller=>"confirmation", :action=>"confirmation",:from=>"address_book",:id=>@address_book.id)
    elsif request.put? || request.post?
      if params[:add_contact]
        if params[:contacts].present? && params[:contacts].strip != "="
        #InlineCsvImporter.new(params[:contacts],@address_book).import
          CsvImporter.new(@address_book, :string => params[:contacts]).delay.import
        else
          flash[:notice] = "Please input information for importing contacts"
         redirect_to :action=>"import"
          return
        end
      elsif params[:upload]
        if params[:file]
          @address_book.import_file = params[:file]
          @address_book.save!
           p @address_book
          #ext = params[:file].original_filename[params[:file].original_filename.rindex(".")+1..-1]
          #if ext.downcase != "csv"
          #  flash[:notice] = "Please upload csv file for importing contacts"
          #  redirect_to :action=>"import"
          #  return
          #end
          #Object.const_get((ext.capitalize + "Importer")).new(@address_book, :file=>params[:file].tempfile.instance_variable_get("@tmpname")).delay.import
        else
           flash[:notice] = "Please input file for uploading contacts"
           redirect_to :action=>"import"
           return
        end
        #Delayed::Job.enqueue Object.const_get((ext.capitalize + "Importer")).new(params[:file].tempfile.instance_variable_get("@tmpname"), @address_book)

      end
      redirect_to :controller=>"confirmation", :action=>"confirmation",:from=>"address_book"
    end
  end

  def show_data
    result = {}
    result["sEcho"] = params["sEcho"]

    @address_book = AddressBook.find(params[:id])
    #result["iTotalRecords"] = address_book.contacts_count
    #result["iTotalDisplayRecords"] = address_book.contacts_count
    #result["aaData"] = []
    ##address_book.contacts.limit(100).offset(2).each do |contact|
    #result["aaData"] << ["", "" ,contact.email,contact.firstname,contact.lastname,contact.name]
    #end
    #puts result.to_json
    #respond_to do |format|
    #format.json {render :json => result.to_json}

    puts "done"
    render(:json =>
               for_data_table(self, ["created_at", "updated_at"] + %w(email firstname lastname name), [["created_at",{:date=>true}], ["updated_at",{:date=>true}]] + %w(email firstname lastname name)) do |contact|
                 ["<%= link_to image_tag(\"delete.png\"), object, :confirm => 'Are you sure?', :method => :delete %>",
                  "<%= link_to image_tag(\"modify.png\"), edit_contact_path(object) %>", contact.email, contact.firstname, contact.lastname, contact.name]
               end)
    #end

  end

  private
  #current unfinished push or nil
  def current_address_book
    AddressBook.where("step is not null").where(:user_id => current_user.id).all[0]
  end

  def for_data_table controller, fields, search_fields=nil, explicit_block=nil, &implicit_block
    params = Hash[*controller.params.map { |key, value| [key.to_s.downcase.to_sym, value] }.flatten]
    search_fields ||= fields
    block = (explicit_block or implicit_block)
    contacts_count = @address_book.contacts_count
    objects = _find_objects params, fields, search_fields


    matching_count = objects.respond_to?(:total_entries) ? objects.total_entries : _matching_count(params, search_fields)

    {:sEcho => params[:secho].to_i,
     :iTotalRecords => contacts_count,
     :iTotalDisplayRecords => matching_count,
     :aaData => _yield_and_render_array(controller, objects, block)
    }.to_json.html_safe
  end

  def _find_objects params, fields, search_fields
    @address_book.contacts.where(_where_conditions params[:ssearch], search_fields).
        includes(_discover_joins fields).
        order(_order_fields params, fields).
        page(_page(params)).per(_per_page(params))
  end

  def _matching_count params, search_fields
    @address_book.contacts.where(_where_conditions params[:ssearch], search_fields).count
  end

  def _discover_joins fields
    joins = Set.new
    object = Contact.new

    fields.each { |it|
      field = it.split('.')

      if (field.size == 2) then
        if object.respond_to?(field[0].to_sym)
          joins.add field[0].to_sym
        elsif object.respond_to?(field[0].singularize.to_sym)
          joins.add field[0].singularize.to_sym
        end
      end
    }

    joins.to_a
  end

  def _where_conditions query, search_fields, join_operator = "OR"
    return if query.blank?

    all_conditions = []
    all_parameters = []

    query.split.each do |term|
      conditions = []
      parameters = []

      search_fields.each do |field|
        next if (clause = _where_condition(term, field.dup)).empty?
        conditions << clause.shift
        parameters += clause
      end

      all_conditions << conditions
      all_parameters << parameters
    end

    [all_conditions.map { |conditions| "(" + conditions.join(" #{join_operator} ") + ")" }.join(" AND "), *all_parameters.flatten]
  end

  def _where_condition query, field
    return [] if query.blank?

    if field.is_a? Array
      options = field.extract_options!

      if options[:split]
        _split_where_condition query, field, options[:split]
      elsif options[:date]
        _date_where_condition query, field.first
      else
        _where_conditions(query, field, "AND")
      end
    else
      ["UPPER(#{field}) LIKE ?", "%#{query.upcase}%"]
    end
  end

  def _date_where_condition query, field
    begin
      ["#{field} = ?", Date.parse(query)]
    rescue ArgumentError
      []
    end
  end

  def _split_where_condition query, fields, splitter
    conditions = []
    parameters = []
    split_query = query.split splitter

    if split_query.size == fields.size
      fields.map do |f|
        conditions << "UPPER(#{f}) LIKE ?"
        parameters << "%#{split_query.shift.upcase}%"
      end

      ["(" + conditions.join(" AND ") + ")", *parameters]
    else
      []
    end
  end

  def _order_fields params, fields
    direction = params[:ssortdir_0] == "asc" ? "ASC" : "DESC"
    %{#{fields[params[:isortcol_0].to_i]} #{direction}}
  end

  private

  def _yield_and_render_array controller, objects, block
    objects.map do |object|
      block[object].map do |string|
        controller.instance_eval %{
            Rails.logger.silence do
              render_to_string :inline => %Q|#{string}|, :locals => {:object => object}
            end
          }
      end
    end
  end

  def _page params
    params[:idisplaystart].to_i / params[:idisplaylength].to_i + 1
  end

  def _per_page params
    case (display_length = params[:idisplaylength].to_i)
      when -1 then
        self.count
      when 0 then
        25
      else
        display_length
    end
  end

end

app/helpers/address_books_helper.rb
# -*- encoding : utf-8 -*-
module AddressBooksHelper
end

app/views/address_books/_agree_provision.html.erb
<%= form_for(@address_book) do |f| %>
    <fieldset>
      <legend><h4>Provision</h4></legend>
      <p>
        PushSurvey has a zero-tolerance spam policy. Subscriber accounts will be terminated for sending unsolicited
        email messages. This means that all recipients sent to must have opted-in to receiving communications from you,
        the sender.

        You can only use PushSurvey to send emails to lists of people that gave you permission to email them. So if you
        don't have proof that each recipient on your list opted-in for your emails, don't import them into PushSurvey.

        We prohibit the use of harvested mailing lists. PushSurvey will terminate accounts violating this prohibition.
        We prohibit the use of third-party, purchased, or rented mailing lists unless you are able to provide proof that
        individuals on the list have opted-in to receiving emails of the type you will be sending them.
        You cannot mail to newsgroups, message boards, distribution lists or unsolicited email addresses.
        You agree to only use PushSurvey in association with an established list of permission based opt-in email
        addresses. We provide use of PushSurvey only to those subscribers who follow our strict anti-spam policy.
        You agree that you shall not utilize PushSurvey to send any commercial electronic mail message to any recipient
        who has opted out, unsubscribed or otherwise objected to receiving such messages from you or another party on
        whose behalf you may be commissioned.
      </p>
      <hr/>
      <p style="text-align:center;">
        <% hidden_field_tag "to_import" %>
        <%= f.submit "I Agree with the terms of use" %>
      </p>
    </fieldset>
<% end %>

app/views/address_books/_form.html.erb
<%= form_for(@address_book) do |f| %>
  <% if @address_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address_book.errors.count, "error") %> prohibited this address_book from being saved:</h2>

      <ul>
      <% @address_book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/address_books/_name.html.erb
<div class="span-12">
  <%= form_for(@address_book) do |f| %>
      <% if @address_book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@address_book.errors.count, "error") %> prohibited this address_book from being
              saved:</h2>

            <ul>
              <% @address_book.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <fieldset>
        <legend><h4>Add New List</h4></legend>
        <br/>

        <div class="field">
          <p><%= f.label :name, "Create address name" %></p>

          <p><%= f.text_field :name %></p>
        </div>
        <hr/>
        <div class="actions">
          <%= f.submit %>
        </div>
      </fieldset>
  <% end %>
</div>
<div class="span-12 last">
  <fieldset>
    <legend><h4>Note</h4></legend>
    <ul id="contenta">
      <li class="conFocus">
        Create a new Address Book and give it a unique name. <br/><br/>
        Please pay attention that the maximum data storage of every Address Book is 30,000 which can be up to 100,000 in
        the next upgrade.
      </li>
    </ul>
  </fieldset>
</div>

app/views/address_books/edit.html.erb
<br />
<br />
<hr />
<div class="span-12 border">
    <h2>List Summary</h2>
    <h6>List Name&nbsp;&nbsp;&nbsp;&nbsp;
      <%= form_for(@address_book) do |f| %>
   <% if @address_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address_book.errors.count, "error") %> prohibited this address_book from being saved:</h2>

      <ul>
      <% @address_book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <%= f.text_field :name %>


    <%= f.submit :value => "Save" %>

<% end %>

    </h6>
    <h6>Modified On&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#666"><em><%= @address_book.updated_at %></em></span></h6>
    <h6>Total Count&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#666"><em><span style="color:#F60"><%= @address_book.contacts_count || 0 %>&nbsp;&nbsp;</span>contact</em></span></h6>
</div>
<div class="span-12 last">
<hr class="space" />
    <h6><%= link_to "+Import Contacts",  import_address_book_path(@address_book)%></h6>
    <h6><%= link_to "!Export Contacts", export_address_book_path(@address_book) %></h6>
</div>
<hr class="space">
<hr />
<div id="container">
    <div id="demo">
        <table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
            <thead>
                <tr>
                    <th>Opt-Out</th>
                    <th>Delet</th>
                    <th>Modify</th>
                    <th>Email Address</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Custom Value</th>
                </tr>
            </thead>
            <tbody>
                <% @address_book.contacts.each do |contact| %>
                <tr class="gradeX">
                    <td><img src="/images/y.gif" /></td>
                    <td><%= link_to image_tag("delete.png"), @address_book, :confirm => 'Are you sure?', :method => :delete %> </td>
                    <td><a href="./modify.html"><img src="/images/modify.png" /></a></td>
                    <td class="center">shin.php@gmail.com</td>
                    <td class="center">Shin</td>
                    <td class="center">Zhang</td>
                    <td class="center">IT</td>
                </tr>
                <% end %>

            </tbody>
            <tfoot>
                <tr>
                    <th>Opt-Out</th>
                    <th>Delet</th>
                    <th>Modify</th>
                    <th>Email Address</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Custom Value</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="spacer"></div>
  </div>

app/views/address_books/import.html.erb
<br/><br/>
<div class="span-12">
  <fieldset>
  <%= form_for  @address_book, :url => import_address_book_path(@address_book), :html=>{:multipart=>true} do |f| %>
      <% if @address_book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@address_book.errors.count, "error") %> prohibited this AddressBook from being saved:</h2>

            <ul>
              <% @address_book.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

        <legend>
          <h4>Add Contacts to <span style="color:#06C"><%= link_to @address_book.name, @address_book %></span></h4>
          </legend>
            <h6>Enter Contacts to be Added</h6>

            <p>Copy and paste in your list of contacts, one contact per line. If you are importing other fields,
              separate
              them by commas, and follow the guidelines below. NOTE: Duplicate emails will automatically be filtered
              out.</p>
            <%= text_area_tag "contacts", @contacts_value %>

            <p>Field Order: email,firstname,lastname,name - 255 characters or less firstname - 50 characters or less
              lastname - 50 characters or less Custom Data - 1000 characters or less Example #1: tjones@myemail.com,
              tom,
              jones, 1001 Example #2: tjones@myemail.com,,,1001</p>

            <p><%= f.submit "Add Contacts", :name => "add_contact" %></p>
            <hr/>
        <%end %>
    <script>
      function upload_file_s3(input) {
        $(":input[name='authenticity_token']",input.form).remove();
        return true;
      }
    </script>
            <% direct_upload_form_for @uploader do |f| %>
            <p>
              <label for="dummy1">Add File</label><br>
              <%= f.file_field "import_file" %><%= f.submit "Upload", :name=>"upload",:onclick=>"return upload_file_s3(this);" %>
            </p>
            <hr/>
        <%end%>

            <p><%= link_to "Back To Address Book", address_books_path %></p>

      </fieldset>

</div>
<div class="span-12 last">
  <fieldset>
    <legend><h4>Note</h4></legend>
    <ul id="contentb">
      <p><%= link_to image_tag("help/addressbookhelp.png", :class=>"addressbookhelp"), root_url %></p>
  </ul>
  </fieldset>
</div>

app/views/address_books/index.html.erb
    <div class="span-3">
        <div class="button">
            <%= link_to "Add New List", new_address_book_path(:type=>"new") %>
        </div>
    </div>
	<hr class="space" />
	<h2 style="color:#999">Address Book</h2>
    <hr />
    <div class="span-24">
	    <p>Address Book Below is a summary of the lists that are currently in your account. To view the details or modify an existing list, just click the name. To add a new list, simply click "Add New List".</p>
    </div>
    <hr />
	<div id="container">
		<div id="demo">
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="datagrid">
                <thead>
                    <tr>
                        <th>List Name</th>
                        <th>Total Count</th>
                        <th>Date Created</th>
                        <th>Date Modified</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @address_books.each do |address_book| %>
                    <tr class="gradeX">
                        <td><%= link_to address_book.name, address_book %></td>
                        <td><%= address_book.contacts_count %></td>
                        <td><%= address_book.created_at %></td>
                        <td class="center"><%= address_book.updated_at %></td>
                        <td class="center">
                          <%= link_to "Export", export_address_book_path(address_book)%>
                          &nbsp;&nbsp;|&nbsp;&nbsp;
                          <%= link_to 'Delete', address_book, :confirm => 'Are you sure?', :method => :delete %>
                        </td>
                    </tr>
                   <% end %>

                </tbody>
                <tfoot>
                    <tr>
                        <th>List Name</th>
                        <th>Total Count</th>
                        <th>Date Created</th>
                        <th>Date Modified</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="spacer"></div>
      </div>

app/views/address_books/new.html.erb
<br/><br/>
<div class="span-24">
      <%= render "#{@address_book.step}"%>
</div>

app/views/address_books/show.html.erb
    <br />
    <br />
    <hr />
    <div class="span-12 border">
        <h2>List Summary</h2>
        <h6>List Name&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#666"><em><%= @address_book.name %></em></span>&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to "Edit Name", edit_address_book_path(@address_book) %></h6>
        <h6>Modified On&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#666"><em><%= @address_book.updated_at %></em></span></h6>
        <h6>Total Count&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#666"><em><span style="color:#F60"><%= @address_book.contacts_count || 0 %>&nbsp;&nbsp;</span>contact</em></span></h6>
    </div>
    <div class="span-12 last">
    <hr class="space" />
        <h6><%= link_to "+Import Contacts",  import_address_book_path(@address_book)%></h6>
        <h6><%= link_to "!Export Contacts", export_address_book_path(@address_book) %></h6>
    </div>
    <hr class="space">
    <hr />
	<div id="container">		
		<div id="demo">
          <script>
            $(document).ready(function() {
    $('#datagrid1').dataTable( {
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<%=url_for :action=>'show_data' %>",
        "sPaginationType": "full_numbers"
    } ).fnSetFilteringDelay();
} );
          </script>
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="datagrid1">
                <thead>
                    <tr>
                        <th>Delete</th>
                        <th>Modify</th>
                        <th>Email Address</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Name</th>
                    </tr>
                </thead>
                <tbody>


                </tbody>
                <tfoot>
                    <tr>
                        
                        <th>Delete</th>
                        <th>Modify</th>
                        <th>Email Address</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Name</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="spacer"></div>		
      </div>